import { AffixDefinition } from './ItemTypes';

export const OFFENSIVE_AFFIXES: AffixDefinition[] = [
  {
    id: 'flat_damage',
    name: 'Added Damage',
    category: 'offensive',
    stat: 'flatDamage',
    minValue: 5,
    maxValue: 25,
    weight: 100,
  },
  {
    id: 'pct_damage',
    name: 'Increased Damage',
    category: 'offensive',
    stat: 'percentDamage',
    minValue: 5,
    maxValue: 20,
    weight: 80,
  },
  {
    id: 'pct_attack_speed',
    name: 'Increased Attack Speed',
    category: 'offensive',
    stat: 'percentAttackSpeed',
    minValue: 3,
    maxValue: 15,
    weight: 70,
  },
  {
    id: 'pct_projectile_speed',
    name: 'Increased Projectile Speed',
    category: 'offensive',
    stat: 'percentProjectileSpeed',
    minValue: 5,
    maxValue: 20,
    weight: 60,
  },
  {
    id: 'pct_crit_chance',
    name: 'Increased Critical Chance',
    category: 'offensive',
    stat: 'percentCritChance',
    minValue: 2,
    maxValue: 8,
    weight: 50,
  },
];

export const DEFENSIVE_AFFIXES: AffixDefinition[] = [
  {
    id: 'flat_hp',
    name: 'Added Health',
    category: 'defensive',
    stat: 'flatHP',
    minValue: 10,
    maxValue: 50,
    weight: 100,
  },
  {
    id: 'pct_hp',
    name: 'Increased Health',
    category: 'defensive',
    stat: 'percentHP',
    minValue: 5,
    maxValue: 15,
    weight: 80,
  },
  {
    id: 'flat_armor',
    name: 'Added Armor',
    category: 'defensive',
    stat: 'flatArmor',
    minValue: 5,
    maxValue: 20,
    weight: 90,
  },
  {
    id: 'hp_regen',
    name: 'Health Regeneration',
    category: 'defensive',
    stat: 'hpRegen',
    minValue: 1,
    maxValue: 5,
    weight: 60,
  },
];

export const UTILITY_AFFIXES: AffixDefinition[] = [
  {
    id: 'pct_move_speed',
    name: 'Increased Movement Speed',
    category: 'utility',
    stat: 'percentMoveSpeed',
    minValue: 3,
    maxValue: 10,
    weight: 70,
  },
  {
    id: 'pct_xp_gain',
    name: 'Increased XP Gain',
    category: 'utility',
    stat: 'percentXPGain',
    minValue: 5,
    maxValue: 15,
    weight: 60,
  },
  {
    id: 'pct_gold_find',
    name: 'Increased Gold Find',
    category: 'utility',
    stat: 'percentGoldFind',
    minValue: 10,
    maxValue: 30,
    weight: 80,
  },
  {
    id: 'pct_cdr',
    name: 'Cooldown Reduction',
    category: 'utility',
    stat: 'percentCDR',
    minValue: 3,
    maxValue: 10,
    weight: 50,
  },
];

export const CONDITIONAL_AFFIXES: AffixDefinition[] = [
  // ── Original 4 conditionals (now with metadata) ──
  {
    id: 'cond_moving_damage',
    name: 'While moving: +damage',
    category: 'conditional',
    stat: 'condMovingDamage',
    minValue: 15,
    maxValue: 15,
    weight: 25,
    conditionType: 'while-moving',
    conditionParams: {},
    buffDuration: 0,
  },
  {
    id: 'cond_on_kill_heal',
    name: 'On kill: heal % max HP',
    category: 'conditional',
    stat: 'condOnKillHeal',
    minValue: 2,
    maxValue: 2,
    weight: 25,
    conditionType: 'on-kill',
    conditionParams: {},
    buffDuration: 0,
  },
  {
    id: 'cond_low_hp_damage',
    name: 'Below 30% HP: +damage',
    category: 'conditional',
    stat: 'condLowHPDamage',
    minValue: 25,
    maxValue: 25,
    weight: 25,
    conditionType: 'low-hp',
    conditionParams: { threshold: 0.3 },
    buffDuration: 0,
  },
  {
    id: 'cond_post_skill_atkspd',
    name: 'After using skill: +attack speed for 3s',
    category: 'conditional',
    stat: 'condPostSkillAtkSpd',
    minValue: 10,
    maxValue: 10,
    weight: 25,
    conditionType: 'after-skill',
    conditionParams: {},
    buffDuration: 3,
  },

  // ── Positioning rewards ──
  {
    id: 'cond_stationary_damage',
    name: 'While standing still: +damage',
    category: 'conditional',
    stat: 'condStationaryDamage',
    minValue: 12,
    maxValue: 20,
    weight: 20,
    conditionType: 'while-stationary',
    conditionParams: { minStationaryMs: 500 },
    buffDuration: 0,
  },
  {
    id: 'cond_close_range_armor',
    name: 'Enemies within 3 tiles: +armor',
    category: 'conditional',
    stat: 'condCloseRangeArmor',
    minValue: 15,
    maxValue: 35,
    weight: 20,
    conditionType: 'distance-close',
    conditionParams: { tileRadius: 3 },
    buffDuration: 0,
  },
  {
    id: 'cond_far_range_proj_speed',
    name: 'No enemies nearby: +projectile speed',
    category: 'conditional',
    stat: 'condFarRangeProjSpeed',
    minValue: 15,
    maxValue: 30,
    weight: 18,
    conditionType: 'distance-far',
    conditionParams: { tileRadius: 5 },
    buffDuration: 0,
  },

  // ── Kill chain / momentum ──
  {
    id: 'cond_kill_streak_speed',
    name: 'Kill streak: +movement speed',
    category: 'conditional',
    stat: 'condKillStreakSpeed',
    minValue: 15,
    maxValue: 25,
    weight: 15,
    conditionType: 'kill-streak',
    conditionParams: { killsRequired: 3, windowSeconds: 4 },
    buffDuration: 5,
  },
  {
    id: 'cond_kill_streak_damage',
    name: 'Kill streak: +damage',
    category: 'conditional',
    stat: 'condKillStreakDamage',
    minValue: 15,
    maxValue: 25,
    weight: 12,
    conditionType: 'kill-streak',
    conditionParams: { killsRequired: 5, windowSeconds: 6 },
    buffDuration: 4,
  },
  {
    id: 'cond_on_kill_cdr',
    name: 'On kill: reduce cooldowns',
    category: 'conditional',
    stat: 'condOnKillCDR',
    minValue: 3,
    maxValue: 8,
    weight: 15,
    conditionType: 'on-kill',
    conditionParams: {},
    buffDuration: 0,
  },

  // ── Health threshold risk/reward ──
  {
    id: 'cond_full_hp_attack_speed',
    name: 'At full HP: +attack speed',
    category: 'conditional',
    stat: 'condFullHPAtkSpd',
    minValue: 8,
    maxValue: 18,
    weight: 20,
    conditionType: 'full-hp',
    conditionParams: {},
    buffDuration: 0,
  },
  {
    id: 'cond_low_hp_regen',
    name: 'Below 30% HP: +health regen',
    category: 'conditional',
    stat: 'condLowHPRegen',
    minValue: 8,
    maxValue: 20,
    weight: 20,
    conditionType: 'low-hp',
    conditionParams: { threshold: 0.3 },
    buffDuration: 0,
  },
  {
    id: 'cond_full_hp_flat_damage',
    name: 'At full HP: +flat damage',
    category: 'conditional',
    stat: 'condFullHPFlatDamage',
    minValue: 8,
    maxValue: 20,
    weight: 18,
    conditionType: 'full-hp',
    conditionParams: {},
    buffDuration: 0,
  },

  // ── Skill interaction / combo ──
  {
    id: 'cond_after_movement_skill_damage',
    name: 'After dash/teleport: +damage',
    category: 'conditional',
    stat: 'condAfterMoveDamage',
    minValue: 12,
    maxValue: 22,
    weight: 18,
    conditionType: 'after-movement-skill',
    conditionParams: {},
    buffDuration: 3,
  },
  {
    id: 'cond_multi_hit_bonus',
    name: 'Hit 3+ enemies: +damage',
    category: 'conditional',
    stat: 'condMultiHitDamage',
    minValue: 10,
    maxValue: 20,
    weight: 15,
    conditionType: 'multi-hit',
    conditionParams: { hitThreshold: 3 },
    buffDuration: 4,
  },
  {
    id: 'cond_after_skill_armor',
    name: 'After using skill: +armor',
    category: 'conditional',
    stat: 'condAfterSkillArmor',
    minValue: 15,
    maxValue: 30,
    weight: 20,
    conditionType: 'after-skill',
    conditionParams: {},
    buffDuration: 3,
  },

  // ── Status effect interactions ──
  {
    id: 'cond_hit_burning_bonus',
    name: 'Hitting burning enemies: +damage',
    category: 'conditional',
    stat: 'condHitBurningDamage',
    minValue: 12,
    maxValue: 22,
    weight: 15,
    conditionType: 'status-on-target',
    conditionParams: { statusEffect: 'burn' },
    buffDuration: 0,
  },
  {
    id: 'cond_hit_slowed_speed',
    name: 'Hitting slowed enemies: +attack speed',
    category: 'conditional',
    stat: 'condHitSlowedAtkSpd',
    minValue: 8,
    maxValue: 16,
    weight: 15,
    conditionType: 'status-on-target',
    conditionParams: { statusEffect: 'slow,chill' },
    buffDuration: 0,
  },
  {
    id: 'cond_on_hit_apply_slow',
    name: 'Hits have chance to slow',
    category: 'conditional',
    stat: 'condOnHitSlow',
    minValue: 6,
    maxValue: 14,
    weight: 18,
    conditionType: 'on-hit',
    conditionParams: { duration: 2 },
    buffDuration: 0,
  },

  // ── Stat breakpoints ──
  {
    id: 'cond_high_vit_regen',
    name: '20+ Vitality: +health regen',
    category: 'conditional',
    stat: 'condHighVitRegen',
    minValue: 5,
    maxValue: 12,
    weight: 15,
    conditionType: 'stat-breakpoint',
    conditionParams: { stat: 'vitality', threshold: 20 },
    buffDuration: 0,
  },
  {
    id: 'cond_high_focus_cdr',
    name: '15+ Focus: +cooldown reduction',
    category: 'conditional',
    stat: 'condHighFocusCDR',
    minValue: 5,
    maxValue: 10,
    weight: 12,
    conditionType: 'stat-breakpoint',
    conditionParams: { stat: 'focus', threshold: 15 },
    buffDuration: 0,
  },
  {
    id: 'cond_high_dex_proj_count',
    name: '25+ Dexterity: +1 projectile',
    category: 'conditional',
    stat: 'condHighDexProjCount',
    minValue: 1,
    maxValue: 1,
    weight: 8,
    conditionType: 'stat-breakpoint',
    conditionParams: { stat: 'dexterity', threshold: 25 },
    buffDuration: 0,
  },

  // ── Defensive / survival ──
  {
    id: 'cond_recently_hit_armor',
    name: 'After taking damage: +armor',
    category: 'conditional',
    stat: 'condRecentlyHitArmor',
    minValue: 20,
    maxValue: 40,
    weight: 20,
    conditionType: 'recently-hit',
    conditionParams: {},
    buffDuration: 4,
  },
  {
    id: 'cond_no_damage_taken_speed',
    name: 'Not hit for 5s: +movement speed',
    category: 'conditional',
    stat: 'condNoDamageTakenSpeed',
    minValue: 15,
    maxValue: 25,
    weight: 18,
    conditionType: 'no-damage-taken',
    conditionParams: { seconds: 5 },
    buffDuration: 0,
  },
];

/** All regular (non-conditional) affixes */
export const REGULAR_AFFIXES: AffixDefinition[] = [
  ...OFFENSIVE_AFFIXES,
  ...DEFENSIVE_AFFIXES,
  ...UTILITY_AFFIXES,
];

/** All affixes including conditionals */
export const ALL_AFFIXES: AffixDefinition[] = [
  ...REGULAR_AFFIXES,
  ...CONDITIONAL_AFFIXES,
];
